/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RecipePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// spoonacular.ts
var import_obsidian = require("obsidian");
var SpoonacularService = class {
  constructor(apiKey, debugMode = false) {
    this.baseUrl = "https://api.spoonacular.com/food/ingredients/map";
    this.apiKey = apiKey;
    this.debugMode = debugMode;
  }
  async categorizeIngredients(ingredients) {
    const cleanKey = this.apiKey ? this.apiKey.trim() : "";
    if (!cleanKey) {
      console.warn("Spoonacular API key is missing.");
      return ingredients.map((name) => ({ name, aisle: "Uncategorized", original: name }));
    }
    try {
      const parseUrl = `https://api.spoonacular.com/recipes/parseIngredients`;
      const body = `ingredientList=${encodeURIComponent(ingredients.join("\n"))}&includeNutrition=false`;
      if (this.debugMode) {
        console.log(`[Recipe Plugin] Sending request to ${parseUrl}`);
        console.log(`[Recipe Plugin] API Key length: ${cleanKey.length}`);
        console.log(`[Recipe Plugin] Body: ${body}`);
      }
      const parseResponse = await (0, import_obsidian.requestUrl)({
        url: parseUrl,
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          "x-api-key": cleanKey
          // Try header auth
        },
        body
      });
      if (this.debugMode) {
        console.log(`[Recipe Plugin] Response Status: ${parseResponse.status}`);
        console.log(`[Recipe Plugin] Response Body:`, parseResponse.json);
      }
      if (parseResponse.status === 200) {
        const data = parseResponse.json;
        return data.map((item) => ({
          name: item.name,
          aisle: item.aisle || "Uncategorized",
          original: item.original
        }));
      } else {
        console.error(`[Recipe Plugin] Spoonacular API error: ${parseResponse.status}`);
        if (this.debugMode)
          console.error(parseResponse.text);
        return ingredients.map((name) => ({ name, aisle: "Uncategorized", original: name }));
      }
    } catch (error) {
      console.error("[Recipe Plugin] Failed to call Spoonacular API:", error);
      if (this.debugMode)
        console.error(error);
      return ingredients.map((name) => ({ name, aisle: "Uncategorized", original: name }));
    }
  }
};

// grocery_manager.ts
var import_obsidian2 = require("obsidian");
var GroceryListManager = class {
  constructor(app, filePath) {
    this.app = app;
    this.filePath = filePath;
  }
  async addIngredients(ingredients, recipeName) {
    const file = await this.getOrCreateGroceryList();
    let content = await this.app.vault.read(file);
    const aisleMap = /* @__PURE__ */ new Map();
    const lines = content.split("\n");
    const newLines = [...lines];
    const newIngredientsByAisle = /* @__PURE__ */ new Map();
    ingredients.forEach((ing) => {
      var _a;
      const aisle = ing.aisle || "Uncategorized";
      if (!newIngredientsByAisle.has(aisle)) {
        newIngredientsByAisle.set(aisle, []);
      }
      (_a = newIngredientsByAisle.get(aisle)) == null ? void 0 : _a.push(`- [ ] ${ing.original} (*${recipeName}*)`);
    });
    for (const [aisle, items] of newIngredientsByAisle) {
      const headerRegex = new RegExp(`^#+\\s*${escapeRegExp(aisle)}`, "i");
      const headerIndex = newLines.findIndex((line) => line.match(headerRegex));
      if (headerIndex !== -1) {
        let insertIndex = headerIndex + 1;
        while (insertIndex < newLines.length && !newLines[insertIndex].match(/^#+\s/)) {
          insertIndex++;
        }
        newLines.splice(insertIndex, 0, ...items);
      } else {
        newLines.push(`
## ${aisle}`);
        newLines.push(...items);
      }
    }
    const updatedContent = newLines.join("\n");
    await this.app.vault.modify(file, updatedContent);
  }
  async getOrCreateGroceryList() {
    const path = (0, import_obsidian2.normalizePath)(this.filePath || "Grocery List.md");
    let file = this.app.vault.getAbstractFileByPath(path);
    if (!file) {
      file = await this.app.vault.create(path, "# Grocery List\n");
    }
    if (file instanceof import_obsidian2.TFile) {
      return file;
    }
    throw new Error(`File at ${path} is not a markdown file.`);
  }
};
function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// main.ts
var DEFAULT_SETTINGS = {
  groceryListPath: "",
  spoonacularApiKey: "",
  debugMode: false
};
var RecipePlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.spoonacularService = new SpoonacularService(this.settings.spoonacularApiKey, this.settings.debugMode);
    this.groceryListManager = new GroceryListManager(this.app, this.settings.groceryListPath);
    this.addCommand({
      id: "add-ingredients-to-grocery-list",
      name: "Add ingredients to Grocery List",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (markdownView) {
          if (!checking) {
            this.parseAndShowIngredients(markdownView.file);
          }
          return true;
        }
      }
    });
    this.addCommand({
      id: "add-manual-grocery-item",
      name: "Add manual item to Grocery List",
      callback: () => {
        new ManualEntryModal(this.app, this).open();
      }
    });
    this.addSettingTab(new RecipeSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.spoonacularService) {
      this.spoonacularService.apiKey = this.settings.spoonacularApiKey;
      this.spoonacularService.debugMode = this.settings.debugMode;
    }
    if (this.groceryListManager)
      this.groceryListManager.filePath = this.settings.groceryListPath;
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.spoonacularService) {
      this.spoonacularService.apiKey = this.settings.spoonacularApiKey;
      this.spoonacularService.debugMode = this.settings.debugMode;
    }
    if (this.groceryListManager)
      this.groceryListManager.filePath = this.settings.groceryListPath;
  }
  async parseAndShowIngredients(file) {
    if (!file)
      return;
    const content = await this.app.vault.read(file);
    const ingredients = this.parseIngredients(content);
    if (ingredients.length === 0) {
      new import_obsidian3.Notice("No ingredients found in this note.");
      return;
    }
    new IngredientModal(this.app, this, file.basename, ingredients).open();
  }
  parseIngredients(content) {
    const lines = content.split("\n");
    const ingredients = [];
    let capturing = false;
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.match(/^#*\s*Ingredients/i) || trimmed.match(/^Ingredients:/i)) {
        capturing = true;
        continue;
      }
      if (capturing && trimmed.match(/^#+\s/)) {
        capturing = false;
      }
      if (capturing) {
        const listMatch = trimmed.match(/^[-*]\s+(.*)/);
        if (listMatch) {
          ingredients.push(listMatch[1].trim());
        }
      }
    }
    return ingredients;
  }
};
var IngredientModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, recipeName, ingredients) {
    super(app);
    this.plugin = plugin;
    this.recipeName = recipeName;
    this.ingredients = ingredients;
    this.selectedIngredients = new Set(ingredients);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: `Add Ingredients from ${this.recipeName}` });
    const listContainer = contentEl.createDiv({ cls: "ingredient-list-container" });
    this.ingredients.forEach((ingredient) => {
      const itemDiv = listContainer.createDiv({ cls: "ingredient-item" });
      const checkbox = itemDiv.createEl("input", { type: "checkbox" });
      checkbox.checked = true;
      checkbox.onchange = () => {
        if (checkbox.checked) {
          this.selectedIngredients.add(ingredient);
        } else {
          this.selectedIngredients.delete(ingredient);
        }
      };
      itemDiv.createSpan({ text: ingredient });
    });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const addButton = buttonContainer.createEl("button", { text: "Add to Grocery List", cls: "mod-cta" });
    addButton.onclick = async () => {
      addButton.setAttr("disabled", "true");
      addButton.setText("Processing...");
      await this.addToGroceryList();
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async addToGroceryList() {
    if (this.selectedIngredients.size === 0) {
      new import_obsidian3.Notice("No ingredients selected.");
      return;
    }
    try {
      const ingredientsList = Array.from(this.selectedIngredients);
      new import_obsidian3.Notice(`Categorizing ${ingredientsList.length} ingredients...`);
      const categorized = await this.plugin.spoonacularService.categorizeIngredients(ingredientsList);
      new import_obsidian3.Notice("Adding to grocery list...");
      await this.plugin.groceryListManager.addIngredients(categorized, this.recipeName);
      new import_obsidian3.Notice("Grocery list updated!");
    } catch (error) {
      console.error(error);
      new import_obsidian3.Notice("Error updating grocery list. Check console.");
    }
  }
};
var ManualEntryModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add Manual Items" });
    contentEl.createEl("p", { text: "Enter ingredients, one per line (e.g., '1 lb green beans')." });
    const textarea = contentEl.createEl("textarea", {
      cls: "manual-entry-textarea",
      attr: { rows: "10", style: "width: 100%;" }
    });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container", attr: { style: "margin-top: 10px;" } });
    const addButton = buttonContainer.createEl("button", { text: "Add to Grocery List", cls: "mod-cta" });
    addButton.onclick = async () => {
      const text = textarea.value.trim();
      if (!text) {
        this.close();
        return;
      }
      const ingredients = text.split("\n").map((l) => l.trim()).filter((l) => l.length > 0);
      addButton.setAttr("disabled", "true");
      addButton.setText("Processing...");
      try {
        new import_obsidian3.Notice(`Categorizing ${ingredients.length} ingredients...`);
        const categorized = await this.plugin.spoonacularService.categorizeIngredients(ingredients);
        new import_obsidian3.Notice("Adding to grocery list...");
        await this.plugin.groceryListManager.addIngredients(categorized, "Manual Entry");
        new import_obsidian3.Notice("Grocery list updated!");
        this.close();
      } catch (error) {
        console.error(error);
        new import_obsidian3.Notice("Error updating grocery list. Check console.");
        addButton.removeAttribute("disabled");
        addButton.setText("Add to Grocery List");
      }
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var RecipeSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Recipe Plugin Settings" });
    new import_obsidian3.Setting(containerEl).setName("Grocery List Path").setDesc('Path to the grocery list file (e.g., "Grocery List.md" or "Folder/List.md"). Defaults to vault root.').addText((text) => text.setPlaceholder("Grocery List.md").setValue(this.plugin.settings.groceryListPath).onChange(async (value) => {
      this.plugin.settings.groceryListPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Spoonacular API Key").setDesc("API Key for ingredient categorization. Get one at https://spoonacular.com/food-api").addText((text) => text.setPlaceholder("API Key").setValue(this.plugin.settings.spoonacularApiKey).onChange(async (value) => {
      this.plugin.settings.spoonacularApiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Debug Mode").setDesc("Enable verbose logging to the developer console (Ctrl+Shift+I).").addToggle((toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
      this.plugin.settings.debugMode = value;
      await this.plugin.saveSettings();
    }));
  }
};
